# Generated by Django 4.2 on 2023-04-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliweb', '0002_about_clientlogo_comment_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
    ]
