# Generated by Django 4.2 on 2023-04-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliweb', '0003_experince'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='picture',
        ),
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ImageField(upload_to='portfoliweb/assets/images'),
        ),
    ]
