# Generated by Django 4.2 on 2023-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliweb', '0005_about_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='./images'),
        ),
        migrations.AlterField(
            model_name='about',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='./images'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ImageField(upload_to='./images'),
        ),
    ]
