# Generated by Django 4.2 on 2023-04-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliweb', '0006_clientlogo_picture_alter_about_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogo',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
