# Generated by Django 4.2 on 2023-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliweb', '0007_clientlogo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='.'),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=250, null=True),
        ),
    ]
