# Generated by Django 4.2 on 2023-04-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliweb', '0009_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='name',
        ),
    ]
