# Generated by Django 4.2 on 2023-04-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliweb', '0010_remove_socialmedia_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='picture',
            field=models.ImageField(upload_to='./images'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliweb.category'),
        ),
    ]
