# Generated by Django 4.2 on 2023-04-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliweb', '0011_category_portfolio_link_alter_portfolio_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
